service: gestion-empleados-api

frameworkVersion: "3"

provider:
    name: aws
    runtime: nodejs18.x
    lambdaHashingVersion: 20201221
    profile: vavarezdeploy-persona
    stage: ${opt:stage}
    region: ${opt:region}

plugins:
  - serverless-offline

functions:
  getEmpleados:
    handler: infraestructure/handlers/empleados-handler.getEmpleados
    events:
      - http:
          path: empleados
          method: get
  postEmpleados:
    handler: infraestructure/handlers/empleados-handler.postEmpleados
    events:
      - http:
          path: empleados
          method: post
          request:
            schemas:
              application/json: ${file(infraestructure/handlers/schemas/empleados-schema.json)}
  putEmpleado:
    handler: infraestructure/handlers/empleados-handler.putEmpleado
    events:
      - http:
          path: empleados/{id}
          method: put
          request:
            schemas:
              application/json: ${file(infraestructure/handlers/schemas/empleados-schema.json)}
  deleteEmpleado:
    handler: infraestructure/handlers/empleados-handler.deleteEmpleado
    events:
      - http:
          path: empleados/{id}
          method: delete
  getEmpleadoDetalle:
    handler: infraestructure/handlers/empleados-handler.getEmpleadoDetalle
    events:
      - http:
          path: empleados/{id}
          method: get
